#!/bin/bash

# Install tukey portal!
# TODO: Write this in python and make it portable

# Use the last stable Horizon commit
STABLE=true

CONFIGURE_APACHE=true
CREATE_CONSOLE=false

# Last commit of Horizon tested against
HORIZON_COMMIT=3a9b0da489030eaacc6cc0416f92192b74783ac8


# Site specific installation variables

# Where to install MUST be absolute path for linking
BASE_DIR=/home/ubuntu
HORIZON_DIR=horizon3
RUN_USER=ubuntu
RUN_GROUP=ubuntu

cd $BASE_DIR

git clone https://github.com/openstack/horizon.git $HORIZON_DIR

if $STABLE
then
    echo "Using current stable Horizon commit: $HORIZON_COMMIT"
    git checkout $HORIZON_COMMIT
else
    echo "WARNING! Using unstable latest version of Horizon"
fi

# Copy tukey subdir into Horizon 
cp -r $TUKEY_DIR $HORIZON_DIR

cd $HORIZON_DIR

# Apply patches for the stuff we couldn't monkey-patch
patch -p1 < tukey/patches/horizon.patch
patch -p1 < tukey/patches/openstack_dashboard.patch

# Append to 

echo "# Tukey Requirements automatically generated by install.sh 
python-openid
django-openid-auth
psycopg2
python-memcached
" >> tools/pip-requires


if $CONFIGURE_APACHE
then
    # Generate Apache config file openstack-dashboard.conf
    
    echo "# Automatically generated by install.sh
    WSGIScriptAlias / $BASE_DIR/$HORIZON_DIR/openstack_dashboard/wsgi/django.wsgi
    
    WSGIDaemonProcess tukey-portal user=$RUN_USER group=$RUN_GROUP python-path=$BASE_DIR/$HORIZON_DIR:$BASE_DIR/$HORIZON_DIR/.venv/lib/python2.7/site-packages
    
    WSGIProcessGroup tukey-portal
    
    Alias /static $BASE_DIR/$HORIZON_DIR/tukey/static/
    
    <Directory $BASE_DIR/$HORIZON_DIR/openstack_dashboard/wsgi>
      Order allow,deny
      Allow from all
    </Directory>
    
    <Directory $BASE_DIR/$HORIZON_DIR/tukey/static>
      Order allow,deny
      Allow from all
    </Directory>" > tukey/openstack-dashboard.conf 
    
    sudo ln -s $BASE_DIR/$HORIZON_DIR/tukey/openstack-dashboard.conf /etc/apache2/sites-available/
    

    if $CREATE_CONSOLE
    then    
    
        echo "# Automatically generated by install.sh
        NameVirtualHost *:80
        
        
        <Virtualhost *:80>
            ServerName console.opensciencedatacloud.org
        
            ErrorLog /var/log/apache2/console-error.log
            CustomLog /var/log/apache2/console-access.log common
        
            UseCanonicalName On
        
            include /etc/apache2/sites-available/openstack-dashboard.conf
        
        </virtualhost>" > /etc/apache2/sites-available/console.conf

        sudo a2ensite console

    fi

fi
